export interface ResourceMeta {
    scope?: 'root' | 'patient' | 'organization';
    eager?: string[];
    title?: (r: any) => string | null | undefined;
}

export const CISZ_SCHEMA: Record<string, ResourceMeta> = {
    AdverseEvent:               { scope: 'patient', title: (r: any) => { const titleName = r.code?.coding?.[0]?.display || r.code?.text || 'Осложнение'; const cat = (Array.isArray(r.category) ? r.category[0] : r.category)?.coding?.[0]?.display; const catStr = cat ? ` (${cat})` : ''; const rawDate = r.detected || r.occurrenceDateTime; const dateStr = rawDate ? ` от ${rawDate.substring(0, 10).split('-').reverse().join('.')}` : ''; return `${titleName}${catStr}${dateStr}`; }},
    AllergyIntolerance:         { scope: 'patient', title: (r: any) => { const trigger = r.extension?.find((e: any) => e.url?.includes('AllergyTriggerString'))?.valueString || r.extension?.find((e: any) => e.url?.includes('MedicationAllergy'))?.valueReference?.display || r.reaction?.[0]?.extension?.find((e: any) => e.url?.includes('ReactionSubstanceString'))?.valueString || r.type?.coding?.[0]?.display || 'Аллергия / непереносимость'; const crit = r.criticality === 'high' ? ' (Высокий риск)' : ''; const date = r.onsetDateTime ? ` от ${r.onsetDateTime.substring(0, 10).split('-').reverse().join('.')}` : ''; return `${trigger}${crit}${date}`; } },   
    CarePlan:                   { scope: 'patient', title: (r: any) => { const prof = r.meta?.profile?.[0]?.split('/')?.pop() || ''; let mainTitle = r.title; if (!mainTitle) { if (prof === 'Dispanserisation') { mainTitle = (Array.isArray(r.category) ? r.category[0] : r.category)?.coding?.[0]?.display || 'Диспансеризация'; } else if (prof === 'IPR') { mainTitle = 'Программа реабилитации инвалида (ИПР)'; } else if (prof === 'MedExaminReport') { mainTitle = (Array.isArray(r.category) ? r.category[0] : r.category)?.coding?.[0]?.display || 'Протокол медосмотра'; } else if (prof === 'CarePlanRadiotherapy') { mainTitle = 'План лучевой терапии'; } else { mainTitle = 'План лечения'; } } const num = r.identifier?.[0]?.value ? ` №${r.identifier[0].value}` : ''; const rawDate = r.created || r.period?.start; const dateStr = rawDate ? ` от ${rawDate.substring(0, 10).split('-').reverse().join('.')}` : ''; return `${mainTitle}${num}${dateStr}`; }},
    Condition:                  { scope: 'patient', title: r => r.code?.coding?.[0]?.display || r.code?.text },
    Contract:                   { scope: 'patient', title: (r: any) => { const prof = r.meta?.profile?.[0]?.split('/')?.pop() || ''; if (prof === 'PlaceOfCare' || r.authority) { const org = Array.isArray(r.authority) ? r.authority[0]?.display : r.authority?.display; return `${r.title || 'Закрепление'}${org ? `: ${org}` : ''}`; } if (prof === 'RejectionBy') { const target = r.topicReference?.display || r.topic?.display || ''; return `${r.title || 'Отказ от медицинской услуги'}${target ? `: ${target}` : ''}`; } if (prof === 'TaskRejecter') { return `Отмена заказа документов${r.title ? ` (${r.title})` : ''}`; } const topic = r.topicReference?.display || r.topic?.display || ''; const exp = r.expirationType?.coding?.[0]?.display || r.expirationType?.text || ''; return `${r.title || 'Отмена назначения'}${topic ? `: ${topic}` : ''}${exp ? ` (${exp})` : ''}`; }},    
    Device:                     { scope: 'organization', title: (r: any) => { const name = r.name?.[0]?.value || r.displayName || r.definition?.concept?.coding?.[0]?.display || r.definition?.concept?.text || 'Медицинское изделие'; const model = r.modelNumber ? ` (${r.modelNumber})` : ''; const sn = r.serialNumber ? ` [SN: ${r.serialNumber}]` : ''; return `${name}${model}${sn}`; }},    
    DeviceDispense:             { scope: 'patient', title: (r: any) => { const devName = r.device?.concept?.coding?.[0]?.display || r.device?.concept?.text || r.device?.reference?.display || 'Обеспечение медизделием'; const qty = r.quantity?.value !== undefined ? ` (${r.quantity.value} ${r.quantity.unit || ''})` : ''; const rawDate = r.whenHandedOver; const dateStr = rawDate ? ` от ${rawDate.substring(0, 10).split('-').reverse().join('.')}` : ''; return `${devName}${qty}${dateStr}`; }},    
    Organization:               { scope: 'root',    title: r => r.name || r.alias?.[0] },
    Location:                   { scope: 'root',    title: r => r.name },
    Practitioner:               { scope: 'root',    title: r => r.name?.[0]?.text },
    PractitionerRole:           { scope: 'root',    title: r => r.practitioner?.display },
    Patient:                    { scope: 'root',    title: r => r.name?.[0]?.text },
    Encounter:                  { scope: 'patient', title: r => r.type?.[0]?.coding?.[0]?.display || r.type?.[0]?.text },
    ServiceRequest:             { scope: 'patient', eager: ['specimen'], title: (r: any) => `${r.code?.concept?.coding?.[0]?.display || r.code?.coding?.[0]?.display || r.code?.concept?.text || r.code?.text || 'Направление'}${(id => id ? ` (№ ${id})` : '')(r.identifier?.[0]?.value)}${(n => n ? ` (${n} проц.)` : '')(r.extension?.find((e: any) => e.url?.includes('ProcedureNumber'))?.valueUnsignedInt)}${(d => d ? ` от ${d.substring(0, 10).split('-').reverse().join('.')}` : '')(r.authoredOn || r.occurrenceDateTime || r.occurrencePeriod?.start)}` },
    DiagnosticReport:           { scope: 'patient', eager: ['specimen'], title: (r: any) => { const titleName = r.conclusionCode?.[0]?.coding?.[0]?.display || r.code?.coding?.[0]?.display || r.code?.concept?.coding?.[0]?.display || r.code?.text || 'Заключение'; const num = r.identifier?.[0]?.value ? ` (№ ${r.identifier[0].value})` : ''; const rawDate = r.effectiveDateTime || r.effectivePeriod?.start || r.issued; const dateStr = rawDate ? ` от ${rawDate.substring(0, 10).split('-').reverse().join('.')}` : ''; return `${titleName}${num}${dateStr}`; }},   
    Procedure:                  { scope: 'patient', title: (r: any) => `${r.code?.coding?.[0]?.display || r.code?.text || 'Процедура'}${r.occurrencePeriod?.start ? ` от ${r.occurrencePeriod.start.substring(0, 10).split('-').reverse().join('.')}` : (r.occurrenceDateTime ? ` от ${r.occurrenceDateTime.substring(0, 10).split('-').reverse().join('.')}` : '')}` },
    Specimen:                   { scope: 'patient', title: r => `${r.type?.coding?.[0]?.display || 'Биоматериал'}${r.collection?.bodySite?.concept?.coding?.[0]?.display ? ', ' + r.collection.bodySite.concept.coding[0].display.toLowerCase() : ''}${r.identifier?.[0]?.value ? ` (№ ${r.identifier[0].value})` : ''}${r.collection?.collectedDateTime ? ` от ${r.collection.collectedDateTime.substring(0, 10).split('-').reverse().join('.')}` : ''}` },
    Observation:                { scope: 'patient', title: r => r.code?.coding?.[0]?.display || r.code?.text },
    DocumentReference:          { scope: 'patient', title: r => r.description || r.type?.coding?.[0]?.display },
    EpisodeOfCare:              { scope: 'patient', title: r => [({ EpisodeOfTemporaryDisabilitySum: 'Случай ВН', EpisodeOfTemporaryDisability: 'Сведения о ВН', Hospitalisation: 'Госпитализация', DayCare: 'Дневной стационар', EpisodeOfEmergencyCare: 'Скорая помощь' } as any)[r.meta?.profile?.[0]?.split('/').pop() || ''] || r.type?.[0]?.coding?.[0]?.display || r.type?.[0]?.text || 'Эпизод мед. помощи', (id => id && `(№ ${id})`)(r.identifier?.find((i: any) => i.type?.coding?.[0]?.code === 'Team-call-card-number' || i.use === 'usual')?.value || r.identifier?.[0]?.value)].filter(Boolean).join(' ') },
    RelatedPerson:              { scope: 'patient', title: (r: any) => `${(Array.isArray(r.relationship) ? r.relationship[0] : r.relationship)?.coding?.[0]?.display || 'Представитель'}: ${r.name?.[0]?.text || [r.name?.[0]?.family, ...(r.name?.[0]?.given || [])].filter(Boolean).join(' ') || 'Без имени'}` },
    MedicationRequest:          { scope: 'patient', title: r => r.medication?.concept?.coding?.[0]?.display || r.medication?.concept?.text || r.medication?.reference?.display },
    QuestionnaireResponse:      { scope: 'patient', title: (r: any) => r.questionnaire?.includes('ObstetrGynec') || r.meta?.profile?.some((p: string) => p.includes('ObstetrGynec')) ? `Акушерско-гинекологический анамнез${r.authored ? ` от ${r.authored.substring(0, 10).split('-').reverse().join('.')}` : ''}` : (r.questionnaire?.includes('FamilyAnamnesis') ? `Семейный анамнез${r.item?.find((i: any) => i.linkId === '1')?.answer?.[0]?.valueBoolean ? ' (Отягощен)' : ''}${r.authored ? ` от ${r.authored.substring(0, 10).split('-').reverse().join('.')}` : ''}` : 'Анкета') },
    FamilyMemberHistory:        { scope: 'patient', title: (r: any) => `${r.relationship?.coding?.[0]?.display || r.relationship?.text || 'Родственник'}${r.name ? `: ${r.name}` : ''}${r.condition?.[0]?.code?.coding?.[0]?.display ? ` (${r.condition[0].code.coding[0].display})` : (r.condition?.[0]?.code?.text ? ` (${r.condition[0].code.text})` : '')}` },
    DeviceRequest:              { scope: 'patient', title: (r: any) => `${r.code?.concept?.coding?.[0]?.display || r.code?.concept?.text || 'Медицинское изделие'}${r.quantity ? ` (${r.quantity} шт.)` : ''}${r.authoredOn ? ` от ${r.authoredOn.substring(0, 10).split('-').reverse().join('.')}` : ''}` },
    ImmunizationRecommendation: { scope: 'patient', title: (r: any) => `Рекомендации по вакцинации${r.recommendation?.length ? ` (${r.recommendation.length} поз.)` : ''}${r.date ? ` от ${r.date.substring(0, 10).split('-').reverse().join('.')}` : ''}` },
    Immunization:               { scope: 'patient', title: (r: any) => { const vName = r.vaccineCode?.extension?.find((e: any) => e.url?.includes('AdministeredVaccine'))?.valueReference?.display || r.vaccineCode?.coding?.[0]?.display || r.vaccineCode?.text || 'Вакцинация'; const d = r.occurrenceDateTime ? ` от ${r.occurrenceDateTime.substring(0, 10).split('-').reverse().join('.')}` : ''; return `${vName}${d}`; } },
    Medication:                 { scope: 'root', title: (r: any) => `${r.code?.text || r.code?.coding?.[0]?.display || 'Лекарственный препарат'}${r.ingredient?.[0]?.item?.reference?.display ? ` [${r.ingredient[0].item.reference.display}]` : ''}` },
    Flag:                       { scope: 'patient', title: (r: any) => `${r.code?.coding?.[0]?.display || r.code?.text || 'Особая отметка о ВН'}${r.extension?.find((e: any) => e.url?.includes('DateFlagReason'))?.valueDate ? ` от ${r.extension.find((e: any) => e.url?.includes('DateFlagReason')).valueDate.substring(0, 10).split('-').reverse().join('.')}` : ''}` },
    ImagingStudy:               { scope: 'patient', title: (r: any) => `${r.procedure?.[0]?.concept?.coding?.[0]?.display || r.procedure?.[0]?.concept?.text || 'Визуальное исследование'}${r.started ? ` от ${r.started.substring(0, 10).split('-').reverse().join('.')}` : ''}` },
    DeviceDefinition:           { scope: 'organization', title: (r: any) => `${r.modelNumber || 'DICOM-принтер'}${r.identifier?.[0]?.value ? ` (№ ${r.identifier[0].value})` : ''}` },
    List:                       { scope: 'patient', title: (r: any) => `${r.title || 'Список назначенных препаратов'}${r.date ? ` от ${r.date.substring(0, 10).split('-').reverse().join('.')}` : ''}${r.entry?.length ? ` (${r.entry.length} рец.)` : ''}` },
    MedicationStatement:        { scope: 'patient', title: (r: any) => `${r.medication?.extension?.find((e: any) => e.url?.includes('TradeNameMedication'))?.extension?.find((x: any) => x.url?.includes('TradeNameMedicationCode'))?.valueCodeableConcept?.coding?.[0]?.display || r.medication?.concept?.coding?.[0]?.display || r.medication?.concept?.text || 'Отпуск лекарственного средства'}${r.dateAsserted ? ` от ${r.dateAsserted.substring(0, 10).split('-').reverse().join('.')}` : ''}` },
};